# Generated by Django 2.1.5 on 2019-02-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='occupation',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
