# Generated by Django 2.1.5 on 2019-02-15 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='question',
        ),
        migrations.RemoveField(
            model_name='response',
            name='respondent',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
