# Generated by Django 2.1.5 on 2019-02-15 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0002_survey_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Survey')),
            ],
        ),
        migrations.CreateModel(
            name='TextAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='multiple_choice',
            name='field',
        ),
        migrations.RenameField(
            model_name='field',
            old_name='form',
            new_name='survey',
        ),
        migrations.DeleteModel(
            name='Multiple_Choice',
        ),
        migrations.AddField(
            model_name='textanswer',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Field'),
        ),
        migrations.AddField(
            model_name='multiplechoice',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Field'),
        ),
    ]
