# Generated by Django 2.1.5 on 2019-02-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_survey_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multiple_choice',
            old_name='choice',
            new_name='q1',
        ),
        migrations.AddField(
            model_name='multiple_choice',
            name='q2',
            field=models.CharField(default='마이그레이션 중인데 뭘자꾸 입력하라는거야 진쫘', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multiple_choice',
            name='q3',
            field=models.CharField(default='언제까지 입력하라하는거야 좀 그만해~~!!!!!!!!!!!!!!!!!!!!!', max_length=30),
            preserve_default=False,
        ),
    ]
