# Generated by Django 2.1.5 on 2019-02-13 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20190213_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='field_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='survey.Field'),
            preserve_default=False,
        ),
    ]
