# Generated by Django 2.1.5 on 2019-02-14 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20190214_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TextAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='multiple_choice',
            name='field',
        ),
        migrations.AddField(
            model_name='field',
            name='index',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='survey.Index'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='field',
            name='pub_date',
            field=models.DateTimeField(default='', verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Multiple_Choice',
        ),
        migrations.AddField(
            model_name='textanswer',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Field'),
        ),
        migrations.AddField(
            model_name='multiplechoice',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Field'),
        ),
    ]
