# Generated by Django 2.1.5 on 2019-02-14 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20190214_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='form',
        ),
        migrations.DeleteModel(
            name='Field',
        ),
    ]
